module.exports = {
  '1': {
    createdAt: '2020-09-11T20:43:03.537Z',
    updatedAt: '2020-09-11T21:22:50.119Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: ['Normal', 'First Finish', 'Flag Tag'],
        designers: ['Bene', 'Sla', 'Spef'],
        levelPatterns: [],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [],
    username: 'Kopaka',
  },
  '2': {
    createdAt: '2020-09-11T20:47:49.039Z',
    updatedAt: '2020-09-12T19:07:37.900Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: ['First Finish'],
        designers: [],
        levelPatterns: [],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
      {
        battleTypes: [],
        designers: ['insguy'],
        levelPatterns: [],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [],
    username: 'Pab',
  },
  '3': {
    isOn: false,
    notifyList: [
      {
        battleTypes: ['Normal'],
        designers: [],
        levelPatterns: [],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [],
    username: 'Sla',
  },
  '4': {
    createdAt: '2020-09-15T16:49:59.977Z',
    updatedAt: '2020-09-15T16:52:33.354Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: ['Normal'],
        designers: [],
        levelPatterns: [],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [
      {
        battleTypes: ['Normal'],
        designers: ['Chris', 'TL'],
        levelPatterns: [],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    username: 'Bene',
  },
  '5': {
    createdAt: '2020-09-15T17:37:11.563Z',
    updatedAt: '2020-09-15T19:37:39.237Z',
    isOn: true,
    notifyList: [],
    ignoreList: [],
    username: 'Markku',
    minDuration: 0,
    maxDuration: 0,
  },
  '6': {
    createdAt: '2020-09-15T16:49:59.977Z',
    updatedAt: '2020-09-15T16:52:33.354Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: [],
        designers: [],
        levelPatterns: ['JoPi'],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [],
    username: 'Zero',
  },
  '7': {
    createdAt: '2020-09-15T16:49:59.977Z',
    updatedAt: '2020-09-15T16:52:33.354Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: [],
        designers: [],
        levelPatterns: ['[a-zA-Z]+0+1$'],
        battleAttributes: [],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [],
    username: 'Zweq',
  },
  '8': {
    createdAt: '2020-09-15T16:49:59.977Z',
    updatedAt: '2020-09-15T16:52:33.354Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: [],
        designers: [],
        levelPatterns: [],
        battleAttributes: ['seeOthers', 'noTurn'],
        minDuration: 0,
        maxDuration: 0,
      },
    ],
    ignoreList: [],
    username: 'Barryp',
  },
  '9': {
    createdAt: '2020-09-15T16:49:59.977Z',
    updatedAt: '2020-09-15T16:52:33.354Z',
    isOn: true,
    notifyList: [
      {
        battleTypes: ['Normal', 'First Finish'],
        designers: ['Markku', 'Zero', 'Adi'],
        levelPatterns: ['Pob', '.*Zero'],
        battleAttributes: ['seeOthers', 'noTurn'],
        minDuration: 20,
        maxDuration: 40,
      },
    ],
    ignoreList: [],
    username: 'Pawq',
  },
};
