export const MIMETYPES = [
  'image/bmp',
  'text/css',
  'text/csv',
  'image/gif',
  'text/html',
  'image/jpeg',
  'text/javascript',
  'application/json',
  'image/png',
  'application/pdf',
  'image/svg+xml',
  'image/tiff',
  'text/plain',
  'image/webp',
  'application/xhtml+xml',
  'application/xml',
];
